* AccessController doPrivileged wasn't passing RuntimeExceptions
* VirtualInvocation (and others) did throw NoSuchMethodException instead of NoSuchMethodError

* ClassLoader model (which needs to be done!) was missing getResources()

scary problem chain